namespace: cennzx-ui
appName: cennzx-ui
httpPath: /
image:
  repository: docker.io
  name: cennznet/cennzx-ui
  
enableLivenessProbe: false
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds:
  timeoutSeconds:
  periodSeconds:
livenessProbe:
  httpGet:
    path:
    port: 80
  initialDelaySeconds:
  timeoutSeconds:
  periodSeconds:
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:
externalServices:
  - namespace: shared
    name: email-service
service:
  port: 80
autoscaling:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:
nodeSelector: {}
tolerations: []
affinity: {}
requiresInternalEndpoint: true
issueCertificate: true
enableWhitelist: false
rewriteTarget: /
enableWebsocketStickyness: true
k8s_platform: eks

