name: Staging Deploy

on:
  push:
    branches:
      - ipfs_deployment

jobs:
  build_code:
    name: Build Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run Build
      run: |
        yarn install --frozen-lockfile
        CI= yarn build:staging

    - name: Upload build files
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: ./build

  deploy:
    name: Deploy Staging
    needs: build_code
    runs-on: macos-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./build

      - name: Deploy to IPFS
        uses: aquiladev/ipfs-action@v0.1.5
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: CENNZX
        id: IPFS_CID

      - name: Echo IPFS URL
        run: |
          echo $IPFS_CID

#      # This branch updates a dnslink for a domain if the current branch should be deployed to prod.
#      # see https://github.com/ipfs-shipyard/js-dnslink-dnsimple
#      - run: npx dnslink-dnsimple --domain https://cennzx.centrality.me/> --link /ipfs/${{ steps.ipfs.outputs.cid }}
#        env:
#          DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
#        # TODO: change to master once merged.
#        if: github.ref == 'refs/heads/beta'